# Generated by Django 5.0.1 on 2024-03-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_myuser_date_of_brith'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_of_brith',
            field=models.DateField(blank=True, null=True),
        ),
    ]
